# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node

name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: yarn install
      - run: echo "$GITHUB_ACTOR_ID $GITHUB_ACTOR"
      - name: Build
        run: yarn build:legaltech
        env:
          NEXT_PUBLIC_AMPLIFY_REGION: ${{ secrets.NEXT_PUBLIC_AMPLIFY_REGION }}
          NEXT_PUBLIC_AMPLIFY_USER_POOL_API_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_AMPLIFY_USER_POOL_API_CLIENT_ID }}
          NEXT_PUBLIC_AMPLIFY_USER_POOL_API_CLIENT_SECRET: ${{ secrets.NEXT_PUBLIC_AMPLIFY_USER_POOL_API_CLIENT_SECRET }}
          NEXT_PUBLIC_AMPLIFY_USER_POOL_APP_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_AMPLIFY_USER_POOL_APP_CLIENT_ID }}
          NEXT_PUBLIC_AMPLIFY_USER_POOL_ID: ${{ secrets.NEXT_PUBLIC_AMPLIFY_USER_POOL_ID }}
          NEXT_PUBLIC_API_HOST: ${{ secrets.NEXT_PUBLIC_API_HOST }}
          NEXT_PUBLIC_COGNITO_OAUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_COGNITO_OAUTH_DOMAIN }}
          NEXT_PUBLIC_COGNITO_OAUTH_REDIRECT_SIGN_IN: ${{ secrets.NEXT_PUBLIC_COGNITO_OAUTH_REDIRECT_SIGN_IN }}
          NEXT_PUBLIC_CONTACT_US_URL: ${{ secrets.NEXT_PUBLIC_CONTACT_US_URL }}
          NEXT_PUBLIC_ENVIRONMENT: ${{ secrets.NEXT_PUBLIC_ENVIRONMENT }}
          NEXT_PUBLIC_FACTORS_AI: ${{ secrets.NEXT_PUBLIC_FACTORS_AI }}
          NEXT_PUBLIC_GA_TRACKING_ID: ${{ secrets.NEXT_PUBLIC_GA_TRACKING_ID }}
          NEXT_PUBLIC_GOOGLE_ANALYTICS: ${{ secrets.NEXT_PUBLIC_GOOGLE_ANALYTICS }}
          NEXT_PUBLIC_GRAPHGL_API_HOST: ${{ secrets.NEXT_PUBLIC_GRAPHGL_API_HOST }}
          NEXT_PUBLIC_GTM_TAG_ID: ${{ secrets.NEXT_PUBLIC_GTM_TAG_ID }}
          NEXT_PUBLIC_JWT_SECRET: ${{ secrets.NEXT_PUBLIC_JWT_SECRET }}
          NEXT_PUBLIC_LEARN_MORE_URL: ${{ secrets.NEXT_PUBLIC_LEARN_MORE_URL }}
          NEXT_PUBLIC_LTH_PROJECT_NAME: ${{ secrets.NEXT_PUBLIC_LTH_PROJECT_NAME }}
          NEXT_PUBLIC_MEDIA_DOMAIN: ${{ secrets.NEXT_PUBLIC_MEDIA_DOMAIN }}
          NEXT_PUBLIC_MIXPANEL_ENABLED: ${{ secrets.NEXT_PUBLIC_MIXPANEL_ENABLED }}
          NEXT_PUBLIC_MIXPANEL_PROJECT_TOKEN: ${{ secrets.NEXT_PUBLIC_MIXPANEL_PROJECT_TOKEN }}
          NEXT_PUBLIC_PRIVACY_PDF: ${{ secrets.NEXT_PUBLIC_PRIVACY_PDF }}
          NEXT_PUBLIC_RECAPTCHA_ENABLED: ${{ secrets.NEXT_PUBLIC_RECAPTCHA_ENABLED }}
          NEXT_PUBLIC_RECAPTCHA_SITE_KEY: ${{ secrets.NEXT_PUBLIC_RECAPTCHA_SITE_KEY }}
          NEXT_PUBLIC_RESOURCE_IMPORT_SAMPLE_CSV_FILE_URL: ${{ secrets.NEXT_PUBLIC_RESOURCE_IMPORT_SAMPLE_CSV_FILE_URL }}
          NEXT_PUBLIC_REVALIDATE_SECRET_TOKEN: ${{ secrets.NEXT_PUBLIC_REVALIDATE_SECRET_TOKEN }}
          NEXT_PUBLIC_REVIEW_ENABLED: ${{ secrets.NEXT_PUBLIC_REVIEW_ENABLED }}
          NEXT_PUBLIC_SENTRY_DSN: ${{ secrets.NEXT_PUBLIC_SENTRY_DSN }}
          NEXT_PUBLIC_SHARE_FEATURE_ENABLED: ${{ secrets.NEXT_PUBLIC_SHARE_FEATURE_ENABLED }}
          NEXT_PUBLIC_SHOW_ASK_AI: ${{ secrets.NEXT_PUBLIC_SHOW_ASK_AI }}
          NEXT_PUBLIC_SHOW_ENHANCED_LISTING_FORM: ${{ secrets.NEXT_PUBLIC_SHOW_ENHANCED_LISTING_FORM }}
          NEXT_PUBLIC_SHOW_FREE_LISTING_FORM: ${{ secrets.NEXT_PUBLIC_SHOW_FREE_LISTING_FORM }}
          NEXT_PUBLIC_SHOW_REVIEWS: ${{ secrets.NEXT_PUBLIC_SHOW_REVIEWS }}
          NEXT_PUBLIC_SHOW_VENDOR_PORTAL: ${{ secrets.NEXT_PUBLIC_SHOW_VENDOR_PORTAL }}
          NEXT_PUBLIC_SITE_URL: ${{ secrets.NEXT_PUBLIC_SITE_URL }}
          NEXT_PUBLIC_TERMS_PDF: ${{ secrets.NEXT_PUBLIC_TERMS_PDF }}
          NEXT_PUBLIC_TWITTER_USER_TITLE: ${{ secrets.NEXT_PUBLIC_TWITTER_USER_TITLE }}

