# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node

name: Build

on:
  push:
    - release/*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: yarn install
      - run: echo "$GITHUB_ACTOR_ID $GITHUB_ACTOR"
      - name: Build
        run: yarn build
        env:
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
          REACT_APP_APP_NAME: ${{ secrets.REACT_APP_APP_NAME }}
          REACT_APP_VERSION: ${{ secrets.REACT_APP_VERSION }}
