# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node

name: Build

on: ["push" , "workflow_dispatch"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEV_EC2_PEM }}
          known_hosts: ${{ secrets.DEV_EC2_KNOWN_HOSTS }}
          if_key_exists: fail

      - name: Deploy
        run: |
          echo ${{ secrets.DEVELOP_SSH_USER }} ${{ secrets.DEVELOP_SERVER_IP }} ${{ secrets.DEVELOP_SOURCE_LOCATION }}
          ssh ${{ secrets.DEVELOP_SSH_USER }}@${{ secrets.DEVELOP_SERVER_IP }} "cd ${{ secrets.DEVELOP_SOURCE_LOCATION }} && touch manish-test-1.txt

      