# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node

name: Build

on: ["push" , "workflow_dispatch"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: keyishere
          known_hosts: ${{ secrets.DEV_EC2_KNOWN_HOSTS }}
          if_key_exists: fail
      
      - name: Deploy
        run: |
          ssh ${{ secrets.DEVELOP_SSH_USER }}@${{ secrets.DEVELOP_SERVER_IP }} "touch ~/manish-test-1.txt"