# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node

name: Build

on: ["push" , "workflow_dispatch"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - name: Build & Deploy
        env:
            PRIVATE_KEY: ${{ secrets.DEV_EC2_PEM }}
            HOSTNAME: ${{secrets.DEVELOP_SERVER_IP}}
            USER_NAME: ${{secrets.DEVELOP_SSH_USER}}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 400 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${DEVELOP_SSH_USER}@${DEVELOP_SERVER_IP}'

              # Now we have got the access of EC2 and we will start the deploy .
              touch ~/manish-test-1.txt
            '